### ISSUE TITLE
Runinng sample code but doesn't work

### ISSUE THREAD

**Issue by Allan-Nava** [georgejecook/maestro-roku#16]
I'm trying to use your framework but the sample code doesn't work

![Screenshot 2021-05-27 at 15 16 29](https://user-images.githubusercontent.com/22498435/119832492-84910800-befe-11eb-8834-c9ee562527e0.png)

**Comment by Allan-Nava** [comment]
Any news?

**Comment by georgejecook** [comment]
thanks for raising this, I'll look at it this weekend.

**Comment by georgejecook** [comment]
this is now resolved

**Comment by Allan-Nava** [comment]
Is it possible to use it? cause right now I use this example: https://github.com/rokudev/hero-grid-channel

**Comment by georgejecook** [comment]
You can try @Allan-Nava.

Please note: I'm not supporting anyone using maestro, outside of my clients or teams, in any way, for the near future. If you know roku well, or you're very experienced in other technologies, and are happy to take on that challenge and risk, then give it a go.

If not, then I suggest you use something else; I won't be there to guide you - and the docs, the code and the tests are all you have.

**Comment by Allan-Nava** [comment]
> You can try @Allan-Nava.
> 
> Please note: I'm not supporting anyone using maestro, outside of my clients or teams, in any way, for the near future. If you know roku well, or you're very experienced in other technologies, and are happy to take on that challenge and risk, then give it a go.
> 
> If not, then I suggest you use something else; I won't be there to guide you - and the docs, the code and the tests are all you have.

Ok, maybe if the project is stable I can try to refactor all the stuff and try to use it
