### ISSUE TITLE
layoutIndex not correlating with view ordering

### ISSUE THREAD

**Issue by shirinsetayesh** [georgejecook/maestro-roku#335]
- layoutIndex not correlating with view ordering
- when toggling visibility the layoutIndex corrects itself 

recording:
[Screen Recording 2023-03-17 at 2.43.10 PM.zip](https://github.com/georgejecook/maestro-roku/files/11004772/Screen.Recording.2023-03-17.at.2.43.10.PM.zip)

**Comment by georgejecook** [comment]
This is now resolved in https://github.com/georgejecook/maestro-roku/pull/337
