### ISSUE TITLE
Can't clone repo on Windows

### ISSUE THREAD

**Issue by cewert** [georgejecook/maestro-roku#346]
The docs have files with a `:` colon in the filename (i.e. `About:-Bsc-plugin.md`)and because of this the repo can't be cloned on Windows computers.

![maestro-clone-error](https://user-images.githubusercontent.com/16514652/228344343-9d1c6287-be50-465a-b251-74cd3e52aced.PNG)

**Comment by cewert** [comment]
FYI I was able to successfully clone the repo using WSL but Windows is still not happy about it

**Comment by georgejecook** [comment]
resolved
